# typed: false
# frozen_string_literal: true

# This formula is auto-generated by scripts/generate-homebrew-formula.mjs
# Do not edit manually — it will be overwritten on each release.

class Vagaris < Formula
  desc "Vagaris CLI — orchestrate AI agent teams to run a business"
  homepage "https://vagaris.org"
  url "https://registry.npmjs.org/@vagarylabs/vagaris/-/vagaris-0.3.2.tgz"
  sha256 "d76bd4e64457f607a4728fe58a04cc4efb7440ac8b32ee20c386ca24d8e604b2"
  version "0.3.2"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec/"bin/vagaris"
    bin.install_symlink libexec/"bin/vagris"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vagaris --version")
    assert_match version.to_s, shell_output("#{bin}/vagris --version")
  end
end
